name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Python env
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Install library
        run: |
          pip install .[dev]

      - name: Run integration tests for sklearn
        run: |
          estimator_to_primitive integration_test/sklearn_metadata.yml
          PYTHONPATH=$PWD python sklearn_wrap/tests/*.py

      - name: Run integration tests for xgboost
        run: |
          pip install xgboost
          estimator_to_primitive integration_test/xgboost_metadata.yml
          PYTHONPATH=$PWD python xgboost_wrap/tests/*.py
